### PR TITLE
some edits to blurbs, titles

### PR DESCRIPTION
**Pull request by jdebacker**
some edits to blurbs, titles

### CODE REVIEW

**Comment by jdebacker** [comment]
@brendancol last commit updates data to fill in where there were missing values before.  However, I'm still not seeing a bubble for residential buildings.

**Comment by MattHJensen** [comment]
@jdebacker, could you confirm that this PR just needs to be merged and then we need some tweak from @brendancol to make the new residential buildings data show up?  After that we can redeploy to the test app and then send to beta testers? 

cc @talumbau

**Comment by jdebacker** [comment]
@MattHJensen , that's right.  cc @brendancol @talumbau

**Comment by jdebacker** [comment]
@brendancol - found a bug in B-Tax, so committed some new results after that fix.

**Comment by brendancol** [comment]
LGTM

**Pull request merged**
