### PR TITLE
METR box plot

### PR DESCRIPTION
**Pull request by jdebacker**
This PR will replace PR #35.  The PR creates a box plot to visualize corporate tax reform options by representing the marginal effective tax rates that results from changes in the CIT, depreciation schedules, and interest deductibility.

### CODE REVIEW

**Comment by jdebacker** [comment]
@brendancol Would you be able to help with some of the aesthetics here?  The current plot looks like:

mettr_reform_boxplot_thumbnail

You may also want to refactor the code a bit.  I'm going to take a stab at that right now and will add commits to this PR as I find improvements.

cc @MattHJensen

**Comment by jdebacker** [comment]
@MattHJensen One point about corporate reform that I find issue with in much of the policy discussion I've been reading is that with a cash flow tax, the rate has no effect on investment incentives for investments with normal returns (so, e.g., the House GOP plan should consider having a rate above 20% since you can raise revenue without economic distortions).  

Currently, this is not reflected well in this plot because full expensing is not applied to inventories.  So when one selects full expensing (with non-deductibility of interest) they will see the reform bars move as the corporate rate is changed.  This movement is due entirely to inventories which as not expensed immediately.  

From what I understand, the House GOP plan is vague w.r.t. this point.  TPC has interpreted this to mean that expensing does apply to inventories, but I'm not sure that's the intent.

Do you have a suggestion for this plot?  Should it plot METTRs only for structures, equipment, IPP - and not inventories or land?

**Comment by MattHJensen** [comment]
@jdebacker, I think the (first) chart would be most valuable as an explainer for business cash flow taxation generally rather than the House plan specifically. If it is possible to expense inventories and land in B-Tax, then I recommend having expensing apply to everything and plotting METTRs for everything.

**Comment by jdebacker** [comment]
The plot now reflects full expensing for all assets types - to include inventories.

cc @MattHJensen @brendancol

**Comment by MattHJensen** [comment]
Cool!

**Comment by MattHJensen** [comment]
What do you think about adding little numerical labels next to the bars like in the CBO plot? 
image

**Comment by MattHJensen** [comment]
What do you think about doing METTR instead of METR? 

I'm remembering what Len said about CCC:

> The terminology METR and METTR seem odd to me.  I think of METR as including all levels of tax (what you call METTR).  It’s certainly the most relevant for policy analysis.

**Comment by jdebacker** [comment]
@MattHJensen - the numbers reported here are the METTRs (I just follow the language in the updated CBO analysis that terms there METRs.

Re the number- we could do that.  If you view the plot in html, it does have the hover over tooltip that pops up giving you the rates for each dot and, for the max and min values, what asset that value is for.

**Comment by MattHJensen** [comment]
@jdebacker, sorry I didn't see your reply soon. All sounds good. Do you think it makes sense to deploy this to the gallery and play around with it there? As far as I can tell, we could start pitching it now, but maybe we'll notice some formatting issues when we look at the embeddable versions in the gallery. 

cc @brendancol @rrenfrow86

**Comment by jdebacker** [comment]
@MattHJensen - sounds good to me, let's try deploying to gallery.

**Comment by MattHJensen** [comment]
> sounds good to me, let's try deploying to gallery.

@jdebacker, over on FlowDock @brittainhard said he'd help out here.

**Comment by britthard** [comment]
@jdebacker i'll take a stab at getting this deployed.

**Comment by jdebacker** [comment]
Thanks @brittainhard.  Give I'm going to make a few changes to the look.  Working right now.  So wait to merge this PR.

**Comment by britthard** [comment]
@jdebacker cool, let me know when you are ready.

**Comment by jdebacker** [comment]
Updated formatting somewhat.  I'm ready to merge.  Current thumbnail:

mettr_reform_boxplot_thumbnail

**Comment by jdebacker** [comment]
@brittainhard I think it could use some formatting (e.g. better title spanning two lines), but I'm having trouble editing html around bokeh plot.  But maybe we can go back to that after posting to gallery?

**Comment by britthard** [comment]
@jdebacker I could take a look at it if you need another set of eyes. If you're satisfied, though, I think we can go ahead with the deployment.

**Comment by jdebacker** [comment]
@brittainhard , thanks for the offer.  What I wanted to do (and my attempt was via trying to include the template.js script in this PR) was to make the title something like;

`Corporate Income Tax Systems`
`Investment Incentives`

On two lines, preferably centered over the plot.

I think fonts are ok as long as you think they are in line with other OSPC gallery plots.  Not sure if you have suggestions on the buttons - whether the appearance is satisfactory or not.

Matt has suggested having the max and min points on the dot plots labeled, but I think when you view the html version, the hover over tooltips are enough.  But let me know what you think.

Also, we'll add some text for the description in the gallery, but let me know if you think it's not very intuitive.  The idea is to be able to consider different corporate tax systems and compare their effects on the tax rate faced by new investment.

**Comment by MattHJensen** [comment]
One thing I just noticed is that the different colors don't have a key. Also, I've heard that it is better to only use red for displaying losses.

**Comment by jdebacker** [comment]
@MattHJensen - yes, good call.  There should be a key.

Regarding color choice - we were trying to follow what seemed to be the OSPC standard here - blue for baseline, red for reform.

**Comment by britthard** [comment]
@jdebacker taking a look now.

**Comment by britthard** [comment]
@jdebacker if you are talking about having a two-line title here: 
screen shot 2017-02-03 at 1 00 10 pm

That is not doable unless you add two labels with specific coordinates in place of the title. Line breaks do not work with HTML canvas, unfortunately. Let me know if I misunderstood you.

Fonts: The fonts look good to me, and are consistent with the other plots in the gallery.

Buttons: I think the buttons look good where they are.

Min/max labels: I agree, I think the tooltips give enough information.

As for whether the plot is intuitive, I have a couple questions. First, why does the top-most tooltip for the baseline say "Inventories" and the reform tooltip says "Mainframes"? Second, why are there lines between each asset type -- what is the relationship between one asset type and another?

One problem I found, there is a minor text issue here. Bokeh automatically adds colons in the tooltip name, so you end up with `Rate: :`. Small fix.
```
hover = HoverTool(
        tooltips = [
            ("Rate: ", "@percents"),
            ("Asset Type:",  "@industries"),
        ]
    )
```

**Comment by jdebacker** [comment]
@brittainhard Thanks for taking a look.

Re the title - yes, it's too bad that Bokeh doesn't allow line breaks!  The workaround on [this plot](https://github.com/open-source-economics/plots/tree/master/contrib/corp_metr) that I helped with was to have `build.py` call `template.j2`, where the latter file would do some formatting, like have a title with two lines.  I tried doing similar here, but while I got the title to work, I lost the buttons at the bottom.

> First, why does the top-most tooltip for the baseline say "Inventories" and the reform tooltip says "Mainframes"? 

Unless one selects "Expensing" as the depreciation system, inventories have the highest METR for the baseline and reform and all financing.  With full expensing, all assets have the same METR - mainframes as listed as the asset type, probably because they are first in the list.

> Second, why are there lines between each asset type -- what is the relationship between one asset type and another?

Each bar should represent the range of marginal effective tax rates on investments for a given tax policy (the baseline or reform - denoted with the different colors) and for a different type of financing (denoted by the three vertical regions of the graph).  The tooltips tell you the max, min, and average rates across all different categories of assets one could invest in.  

> One problem I found, there is a minor text issue here. Bokeh automatically adds colons in the tooltip name, so you end up with Rate: :. Small fix.

I fixed this just now.

**Comment by britthard** [comment]
Thanks @jdebacker , just wanted to make sure there weren't any errors. I'm ready to merge and deploy if you are satisfied.

**Comment by jdebacker** [comment]
Yes. Go ahead w merge. Thanks.

**Pull request merged**
