### PR TITLE
Fix tooltip for single point

### PR DESCRIPTION
**Pull request by jdebacker**
This PR cleans up the build.py code by removing extraneous elements.

It also sets the column data sources so that only the average is presented when the rates are collapsed to a single point (rather than a line segment).

### CODE REVIEW

**Comment by jdebacker** [comment]
Screenshot:
ss_plot

**Comment by jdebacker** [comment]
@MattHJensen I think this has the fixes we discussed:
1) Updated data to capture latest from B-Tax
2) Toggle for individual rates
3) Updated title
4) Hoverover for data when collapsed to a single point only displays asset name = "Average".

Two minor concerns I have (which we might ignore, but let me know):
1) Rates and get quite negative when excluding individual level.  Thus in order to have axes remain the same scale as user toggles through the options, I had to set the min of the range to -160%
2) I can't get the hover over to display just one asset/rate when the 3 points are collapse to one.  No longer does one see a name of a specific asset in this case, but the average rate is repeated three times.

**Comment by MattHJensen** [comment]
> 1) Updated data to capture latest from B-Tax
> 2) Toggle for individual rates
> 3) Updated title
> 4) Hoverover for data when collapsed to a single point only displays asset name = "Average".
> 

This is all great. 

> I can't get the hover over to display just one asset/rate when the 3 points are collapse to one. No longer does one see a name of a specific asset in this case, but the average rate is repeated three times.

That seems just fine. 

> Rates and get quite negative when excluding individual level. Thus in order to have axes remain the same scale as user toggles through the options, I had to set the min of the range to -160%

What do you think about changing the axes when the user toggles "include individual income taxes"? Would that be easy?

**Comment by jdebacker** [comment]
> What do you think about changing the axes when the user toggles "include individual income taxes"? Would that be easy?

@MattHJensen I'm not inclined to do this.  CBO seems to use METR interchangeably for both the METTR and METR.  I think changing would cause more questions.  IMO it's clear form the "Include Individual Income Taxes".

**Comment by MattHJensen** [comment]
@jdebacker, sorry for the confusion. I meant to say, what do you think about changing the _scales_ of the axes. I'm a little concerned that all of the positive action is compressed in a small space. If the scales changed when that toggle was used, then we'd free up a little space in positive territory when individual income taxes are included. 

I agree that there is no reason to change the axes label.

**Comment by jdebacker** [comment]
@MattHJensen My fault on the misunderstanding.

Here are the two  versions:  [with fixed y-axis range](https://jdebacker.github.io/plot0.html) and [with a changing y-axis](https://jdebacker.github.io/plot2.html).  I think I' minding the changing axes less, but let me know your preference.

**Comment by MattHJensen** [comment]
cool deployment to github.io! I fairly strongly prefer the changing axes. Think this is good to deploy and start pitching now?

**Comment by jdebacker** [comment]
Ok - that change is committed to this PR.  Ready to merge and pitch.

cc @MattHJensen

**Comment by MattHJensen** [comment]
Thanks @jdebacker. Merging. @brendancol or @brittainhard, could one of you deploy this to ospc.org/gallery?

**Pull request merged**
