### PR TITLE
Initial scripts for metr boxplot

### PR DESCRIPTION
**Pull request by jwgarrison**
This creates a new visualization looking at how marginal effective tax rates change under various reforms. Currently a work in progress with only two reforms. More reforms for specified conditions to be added later.

Based on Open Source Economics [plot concepts issue #6](https://github.com/open-source-economics/plot-concepts/issues/6)

### CODE REVIEW

**Comment by jdebacker** [comment]
@jwgarrison Thanks for opening this PR!

@MattHJensen, Justin is a student at USC who has been working on Plot Concept Issue #6.  I think he's got the general idea working.  I recommend he open this PR to start the discussion and to help get some input from the open source policy community.  

To develop more fully before this PR can be merged, we need:
- [ ] Data with multiple reforms that represent combinations of changes in the corporate tax rate, depreciation schedules, and interest deductibility (for me to do).
- [ ] A slider that can accommodate more than one movement.
- [ ] Multiple sliders - one for each of the corp rate (5 notches: [39.6, 35, 25, 15, 0]), depreciation (3 notches: [Economic Depreciation, Current Law, no Bonus Depreciation, 100% expensing]), and interest deductibility (2 notches: [Fully deductible, Not deductible]).
- [ ] Some aesthetic changes.

**Comment by MattHJensen** [comment]
Hi @jwgarrison. Welcome. This plot highlights several important policy lessons. Thanks for taking the lead on it.

**Comment by brendancol** [comment]
@jwgarrison looking good.  I didn't see any change when using the slider though.

screen shot 2016-10-10 at 9 16 56 am

**Comment by jwgarrison** [comment]
The issue I've been having with the slider is that the first time it's used it will change the reform's data source, but then do nothing on subsequent uses. I based it on [this example](https://github.com/bokeh/bokeh/blob/master/examples/howto/interactive_bubble/gapminder.ipynb), but I haven't figured out why it doesn't work here.

**Comment by MattHJensen** [comment]
> The issue I've been having with the slider is that the first time it's used it will change the reform's data source, but then do nothing on subsequent uses. I based it on this example, but I haven't figured out why it doesn't work here.

@jwgarrison, is this still a problem for you? 

cc @brendancol

**Comment by jwgarrison** [comment]
@MattHJensen Bug was being caused by having two variables pointing to the same object when it should have been a copy. That's fixed and I have a version with a full set of rate, depreciation and deductibility options, so I'll update the pull request once I have a chance to look at some anomalies in the data with Dr. DeBacker

**Comment by MattHJensen** [comment]
@jwgarrison said:

> @MattHJensen Bug was being caused by having two variables pointing to the same object when it should have been a copy. That's fixed and I have a version with a full set of rate, depreciation and deductibility options, so I'll update the pull request once I have a chance to look at some anomalies in the data with Dr. DeBacker

Thanks! That's good news.

**Comment by jdebacker** [comment]
@jwgarrison  Thanks for the commits.  This is coming together nicely. Can you share a screenshot here?

**Comment by jwgarrison** [comment]
screen shot 2016-10-20 at 4 53 55 pm

The basic functions are all working, and now it needs some visual and formatting changes such as centering the buttons, changing their styling, and potentially changing the rate options to a slider.

**Comment by MattHJensen** [comment]
@jwgarrison, what's the status on this one? Looks like it is coming along very nicely.

**Comment by MattHJensen** [comment]
@jwgarrison, just checking back again. A once-in-several-decades business tax reform debate is currently taking place. If we get this widget done soon, I think it could educate policymakers and the public about some important interactions and be a major contribution to the public discussion. I expect it will also receive significant media attention (our last widget had a [full story](http://blogs.wsj.com/economics/2016/12/26/republicans-radical-new-business-tax-proposal-simplified-sort-of/) in WSJ about it and was [embedded](http://www.vox.com/2016/12/25/14069822/corporate-tax-border-adjustability) at Vox.com). And it would be a very impressive contribution to a professional portfolio. The kicker is that it seems like it is almost done so all of that is fairly easy to achieve! Feel free to shoot me an email or call if you want to discuss (matt.jensen@aei.org/ 812.320.7648).

**Comment by jdebacker** [comment]
This PR is being replaced by PR #52

**Pull request merged**
