### PR TITLE
Scripts to generate MTR skyline plots 

### PR DESCRIPTION
**Pull request by GoFroggyRun**
The `main.py` generates a new visualization for marginal tax rate plots. Two reforms are based on candidates' tax proposals. (Not yet labeled) 

I'm having some issues to make this plot interactive, meaning that there will be **no change** when I change the selection tool. Not sure where I got wrong. 

@brendancol, Could you please advice?

cc @MattHJensen

### CODE REVIEW

**Comment by brendancol** [comment]
General Items:
- [ ] add info.yml file
- [ ] add environment.yml file
- [ ] add more descriptive plot title / id

A couple of tips on wiring up interactivity through the `Select` component:
- `.on_change()` is meant for Bokeh _Server_ apps, for this case, you want to use a `CustomJS` callback

The general idea would be:

``` python
source = ColumnDataSource(data=dict(sc=[]))
callback1 = CustomJS(args=dict(single_source=src1, joint_source=src2), code="""
        ... callback logic ...
        source.trigger('change');
    """)

select1 = Select(title="Cat1", value=categories[0], options=categories, callback=callback1)
```

**Comment by GoFroggyRun** [comment]
@brendancol:

Thanks for your feedback on the callback function. I am able to generate interactive visualization using `CustomJS` function. 

I'll address general issues, as well as make cosmetic modifications, very soon.

cc @MattHJensen

**Comment by GoFroggyRun** [comment]
@talumbau, could you advise how to deploy this plot to the ospc test app?

**Comment by GoFroggyRun** [comment]
screen shot 2016-11-03 at 8 55 25 pm

A preview of updated plot.

**Comment by MattHJensen** [comment]
@GoFroggyRun, could you check out these conflicts?

**Comment by GoFroggyRun** [comment]
@MattHJensen Now good to go.

**Pull request merged**
