### PR TITLE
Filled in descriptions and added attributes for credits to info.yml

### PR DESCRIPTION
**Pull request by MattHJensen**
@brendancol and @talumbau, what do you think of these new credit attributes and the length/content of the descriptions? 

Based on @brendancol's suggestion https://github.com/open-source-economics/plots/issues/11#issuecomment-227289446 I am thinking we could pull the info from these attributes into the text that is displayed on the plot (long_description, concept credit, development_credit, OSS_credit, and a hosting credit for OSPC would be added to all plots in the gallery.) 

If we proceed this way, an outstanding question is how to store hyperlink information in info.yml. For instance, we would probably want links for the names of people and the names of key OSS projects.

### CODE REVIEW

**Comment by talumbau** [comment]
This looks good to me. Would the long description go in place of the current filler text at the bottom, as shown on the test app?

screen shot 2016-06-29 at 9 47 18 am

I just did a quick experiment and confirmed I can get that text to render on the web application as live HTML code, so for example, you would put links in the description with `<a href="www.google.com">the link</a>"` and it will render with the link on the web app.

**Comment by MattHJensen** [comment]
> Would the long description go in place of the current filler text at the bottom, as shown on the test app?

Yes. 

> I just did a quick experiment and confirmed I can get that text to render on the web application as live HTML code, so for example, you would put links in the description with <a href="www.google.com">the link</a>" and it will render with the link on the web app.

Excellent. That's what I was hoping. Just added these in a new commit. 

Removing the WIP tag.

**Comment by talumbau** [comment]
Ok, great. @brendancol for your reference I am modifying the template on the web app side to do something like the following:

```
<p> {{ long_description | safe }} </p>
```

this appears to work well. Let me know if you have other ideas.

**Comment by talumbau** [comment]
OK @MattHJensen would you like me to merge this and deploy to the test app so you can take a look at the full viz as it would be on the site?

**Comment by MattHJensen** [comment]
That'd be great.

**Pull request merged**
