### PR TITLE
Create main.py

### PR DESCRIPTION
**Pull request by darthur11**

### CODE REVIEW

**Comment by brendancol** [comment]
@darthur11, can you give some more info on the objectives of this PR?

**Comment by darthur11** [comment]
Hi, 
I'm from upwork.com. In description has been written to make pull request. I just made it. 
On this weekend i wanted to finish this project.

**Comment by brendancol** [comment]
@darthur11 can you provide a screenshot in this PR of your plot?

**Comment by MattHJensen** [comment]
Closing given no further feedback from @darthur11.

**Pull request closed without merging**
