### PR TITLE
Metr (bcollins)

### PR DESCRIPTION
**Pull request by brendancol**

### CODE REVIEW

**Comment by MattHJensen** [comment]
@brendancol, is this ready for @jdebacker to review? Could you post a screenshot of what it would look like?

**Comment by brendancol** [comment]
screen shot 2016-09-13 at 10 59 21 am

**Comment by jdebacker** [comment]
@brendancol - looking nice!  I like the colors for baseline and reform, and the horizontal line at zero. 

A couple comments:
1) Since it shows the baseline and reform, the title will need updating.
2) If we could do some asset category labels such as "equipment" and "structures" (e.g. left aligned and in bold above asset groups), we could save some horizontal space by not having to repeat works like equipment, structures, and buildings.
3) We'll need some text describing the color scheme (and maybe the bubble size).

**Comment by brendancol** [comment]
reform values in blue obviously look suspicious, I might just be using the wrong field.  @Jason, for reform values, which field should I use for x?  Example:

```
p.circle(x='metr_c',
         y='asset_category',
         color="#336699",
         size='size',
         line_color="white",
         source=reform_source,
         alpha=.4)
```

**Comment by brendancol** [comment]
@Jason, what do you think an appropriate title would be?  Maybe _Before and After Reforms: Marginal Effective Tax Rates on Corporate Investments_

**Comment by jdebacker** [comment]
@brendancol - the reform values look correct.  That reform eliminates the tax wedge on new investments so the METR should be zero under reform.

Re title, maybe just "Marginal Effective Tax Rates on Corporate Investments" - then the legend will give the before/after reform. This also allows us flexibility if we want t make dynamic so that can change come reform parameters.

**Comment by MattHJensen** [comment]
@jdebacker, do you have a preference for using METRs rather than METTRs? I find METTRs to be more informative.

**Comment by jdebacker** [comment]
@MattHJensen , I can see your point.  However, maybe we begin with METRs because:
1) This is what I find most people present
2) There are less assumptions going into METRs (eg. about the effects of taxes on dividend financed investments, about who the marginal investor is, etc)
3) If we are just focusing in corps (as here) then it's nice to see how corp income tax parameters affect investment incentives.
4) We don't yet have the UI set up for individual taxes, so perhaps it makes sense to focus on the METRs for now, since they aren't as affected by these.

**Comment by MattHJensen** [comment]
@jdebacker, it seems hard to communicate the METR. For example, this sentence is misleading: 

> That reform eliminates the tax wedge on new investments so the METR should be zero under reform. 

We could say, "that reform eliminates the tax wedge on new investments _stemming from the corporate income tax_, although there is still a tax wedge stemming from other taxes which are not included in this measure," but that is a mouthful. 

Similarly, if we display METRs then it makes it hard to illustrate the difference between the House Republican and Trump plans and a true consumption tax. 

Regarding your points:
1. As far as I can tell, CBO uses METTRs: https://www.cbo.gov/sites/default/files/113th-congress-2013-2014/reports/49817-Taxing_Capital_Income_0.pdf. 
2. That's true, but couldn't we just footnote those? Subsequent versions of the chart could highlight the influence of each assumption.  
3. In some ways I think METTRs more accurately show how corp income tax parameters affect investment incentives, because the user can see what the METTR is w and w/o the corporate income tax. 
4. I think it's fine to just say coming soon for the IIT parameters. METTRs would show the importance of what's coming, whereas METRs undermine it. 

Granted, we have a very similar issue on the TC side because we only calculate MTRs from individual income and payroll taxes, but I would FAR prefer to include other marginal tax rates and we are currently going to a great effort to do so -- we already have the capability with B-Tax, so it seems like a waste not to use it. 

One option would be to have a toggle for METR/METTR, but I'm not sure how much that would complicate development and the user interface.

**Comment by jdebacker** [comment]
@MattHJensen - I'd rather not complicate with a toggle. And I think you've convinced me that the default should be the METTR.  I'll be in touch with @brendancol about updating to reflect this measure.

**Comment by brendancol** [comment]
@jdebacker @MattHJensen One concept Im exploring is separating Equipment and Structures into different plot so they can be visually separated.

screen shot 2016-09-14 at 1 59 52 pm

**Comment by brendancol** [comment]
@jdebacker i switched to using the `mettr_c` field and looks like datashift by 10%.  Is this the correct field for METTR
screen shot 2016-09-14 at 11 10 32 pm

**Comment by jdebacker** [comment]
@brendancol  - ok - I think that's right for the old data.  Will look different with reforms I passed along.

With new data:
1) Don't worry about line at zero or showing negative rates - they won't be in that range with the METTR metric.
2) Re subtitle (for graph with new data): how about: "Going, going, gone: The phaseout of bonus depreciation" (or just "The phase out of bonus depreciation" if the former too long)
3) With new data/reform we can name baseline "2016" and reform with the year the slider is set to.

**Comment by brendancol** [comment]
> 1) Don't worry about line at zero or showing negative rates - they won't be in that range with the METTR metric.

@Jason, so I should remove the line at zero correct?

**Comment by jdebacker** [comment]
> @Jason, so I should remove the line at zero correct?

Correct, since we've moved to this different measure of effective tax rates.  It may make a comeback depending on the reform (i.e. if we go to a pure consumption tax), but please drop for this visual.

**Comment by brendancol** [comment]
@Jason, In the new data, I see `Land` and `Inventories` categories.  Should this be ignored or included?  If included, are they considered `equipment` or `structures`?

@Jason, also, I don't see the `assets` field in the new data which was used to set the bubble size. Which field should I use of this?  Would `assets_c` field be correct?

**Comment by jdebacker** [comment]
@brendancol let's exclude for now to focus on equip and structures.  I forgot whether those were dropped here with intellectual property or not.  But do please drop land, inventories, and IP.  Thanks.

**Comment by brendancol** [comment]
@Jason,  The plot has gotten somewhat muddy after changing to the `mettr` values, basically because reform values now vary so much that my eye cannot track the change.  am I right to say that we should abandon the reform vs. baseline and show only 1 `mettr` year bubbles based on the value of the slider?

screen shot 2016-09-15 at 1 29 54 pm

**Comment by jdebacker** [comment]
Sounds good.  Other option is to abandon all asset types, and just have one bubble per category (so create a weighted avg for each category).  Don't get the variance with in asset category, but do get variance across category and could plot multiple reforms with baseline.  Maybe your suggestion is easier to jump off too.

**Comment by brendancol** [comment]
@Jason, I think you have a good idea here.  By aggregating categories, and having only 1 bubble per asset category, that will clear up the muddy plot issue and the effects of reforms will be easily to understand.  Should this be the mean `mettr_c` within the category weighted by the `assets_c` field?

**Comment by jdebacker** [comment]
Yes assets to weight. Bubble size will be related to the sum of asset_c by category.

**Comment by jdebacker** [comment]
@brendancol, here's my latest:
thumbnail

Here are some issues:
1) Why doesn't it have bubbles for mining and drilling structure?  Their assets are not zero.
2) I need to fix something in B-Tax, total assets in corporate residential buildings are being dropped somewhere along the line.
3) The legend needs to be moved.
4) I can't get it to plot "short_category" instead of "asset_category" for the y labels.  I can't tell why this won't work, but if I change `y='asset_category'` to `y='short_category'`, only a couple categories have bubbles.
5) Longer lived property (greater than 20 years) will not have any changes.  How to represent this?  Right now it's just one bubble with colors mixed.  Should we offset just slightly?  Set to different color and put "2016+" in legend?

Also, how do the aesthetics look to you?  Is this the right plot for this info?  It's nice to see variation in asset size across categories, but something about the fact that the bubbles are so small or similar in size across categories or that they are constant along a line is bothering me.  Should we up the variation in bubble size?  Or maybe just increase the size?

**Comment by brendancol** [comment]
Example plot now deployed to demo site: https://ospc-taxes7.herokuapp.com/gallery/corp_mettr/

**Pull request merged**
